/*
  Warnings:

  - You are about to alter the column `id` on the `Match` table. The data in that column will be cast from `String` to `Int`. This cast may fail. Please make sure the data in the column can be cast.
  - Added the required column `customerId` to the `Order` table without a default value. This is not possible if the table is not empty.
  - Added the required column `orderId` to the `Reservation` table without a default value. This is not possible if the table is not empty.
  - Added the required column `ticketsId` to the `Reservation` table without a default value. This is not possible if the table is not empty.
  - Added the required column `matchId` to the `Ticket` table without a default value. This is not possible if the table is not empty.

*/
-- AlterTable
ALTER TABLE "Order" ADD COLUMN     "customerId" STRING NOT NULL;

-- AlterTable
ALTER TABLE "Reservation" ADD COLUMN     "orderId" STRING NOT NULL;
ALTER TABLE "Reservation" ADD COLUMN     "ticketsId" STRING NOT NULL;

-- AlterTable
ALTER TABLE "Ticket" ADD COLUMN     "matchId" INT4 NOT NULL;

-- RedefineTables
CREATE TABLE "_prisma_new_Match" (
    "id" INT4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "name" STRING NOT NULL DEFAULT 'TBD',
    "roundNumber" INT4 NOT NULL,
    "Date" TIMESTAMP(3) NOT NULL,
    "location" STRING NOT NULL,
    "homeTeam" STRING NOT NULL,
    "homeTeamContinents" STRING NOT NULL,
    "awayTeam" STRING NOT NULL,
    "awayTeamContinents" STRING NOT NULL,
    "group" STRING NOT NULL,
    "homeTeamScore" INT4,
    "awayTeamScore" INT4,
    "rank" INT4 NOT NULL,

    CONSTRAINT "Match_pkey" PRIMARY KEY ("id")
);
INSERT INTO "_prisma_new_Match" ("Date","awayTeam","awayTeamContinents","awayTeamScore","group","homeTeam","homeTeamContinents","homeTeamScore","id","location","name","rank","roundNumber") SELECT "Date","awayTeam","awayTeamContinents","awayTeamScore","group","homeTeam","homeTeamContinents","homeTeamScore","id","location","name","rank","roundNumber" FROM "Match";
DROP TABLE "Match" CASCADE;
ALTER TABLE "_prisma_new_Match" RENAME TO "Match";

-- AddForeignKey
ALTER TABLE "Ticket" ADD CONSTRAINT "Ticket_matchId_fkey" FOREIGN KEY ("matchId") REFERENCES "Match"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Order" ADD CONSTRAINT "Order_customerId_fkey" FOREIGN KEY ("customerId") REFERENCES "Customer"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Reservation" ADD CONSTRAINT "Reservation_orderId_fkey" FOREIGN KEY ("orderId") REFERENCES "Order"("id") ON DELETE RESTRICT ON UPDATE CASCADE;

-- AddForeignKey
ALTER TABLE "Reservation" ADD CONSTRAINT "Reservation_ticketsId_fkey" FOREIGN KEY ("ticketsId") REFERENCES "Ticket"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
